### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by octocatblain**
- update froms width
- add contact section
- add login page
- add back to top button

### CODE REVIEW

**Comment by Chareeef** [comment]
I'll review as  soon as possible

**Review by Chareeef — CHANGES_REQUESTED** [review]
It's an awesome work Blain. 
I really loved it. 
I just would prefer a more related blood donation related pictures in the home page.
And also you need to have 8 blood category options in donations request, though I need you to kindly explain how wd should handle these requests. 
Login should also differentiate between log in as a donor or transfusion center. But its design is great. 
You're the best.

**Comment by KENC0DE** [comment]
And also on the header bar this tab `[ Donate Stations Contact ]` change their color to bright red or something, it is uncomfortable for the eye.

**Comment by octocatblain** [comment]
> It's an awesome work Blain. I really loved it. I just would prefer a more related blood donation related pictures in the home page. And also you need to have 8 blood category options in donations request, though I need you to kindly explain how wd should handle these requests. Login should also differentiate between log in as a donor or transfusion center. But its design is great. You're the best.

i will check on this @Chareeef

**Pull request merged**
